/**
 * POST /api/belege/upload
 *
 * Multi-File-Upload-Endpoint fuer Belege.
 *
 * Workflow pro Datei:
 *  1. Multer schreibt Datei nach OS-tmpdir (autogenerated filename)
 *  2. SHA-256 ueber den tmp-File berechnen
 *  3. Duplicate-Check via duplicateCheckService.findBySha256
 *     - Treffer  → tmp-File loeschen, im Response als duplicate markieren, weiter zur naechsten Datei
 *     - kein Treffer → Storage-Verzeichnis (~/.local/share/.../YYYY/MM/) sicherstellen
 *  4. Datei nach finalen Pfad mit DJ-konformem Namensschema verschieben
 *  5. Receipt-Row anlegen (status='ocr_pending') + receipt_files-Eintrag
 *  6. setImmediate(...) startet OCR-Job im Hintergrund:
 *     - ocrService.ocrFile → receiptParserService.parse → receiptService.applyOcrResult
 *     - Bei Fehler → receiptService.markOcrFailed (status zu_pruefen)
 *  7. Upload-Response 201 mit Liste aller Receipt-IDs (auch Duplikate)
 *
 * Sicherheit:
 *  - Multer hard-limit 100 MB; settings-basiertes max_upload_size_mb laeuft pro File nach.
 *  - fileFilter erlaubt nur .pdf/.jpg/.jpeg/.png (path.extname → letzter Suffix; .pdf.exe wird abgelehnt).
 *  - sanitizeForFilename garantiert ASCII-Slug ohne Path-Traversal-Chars.
 */
import { Router } from 'express';
import multer from 'multer';
import path from 'path';
import fs from 'fs/promises';
import os from 'os';
import db from '../db/connection';
import { sha256OfFile, ensureStorageDir } from '../lib/files';
import { sanitizeForFilename } from '../lib/filenames';
import { receiptService } from '../services/receiptService';
import { ocrService } from '../services/ocrService';
import { receiptParserService } from '../services/receiptParserService';
import { duplicateCheckService } from '../services/duplicateCheckService';
import type { Request } from 'express';

interface KvRow {
  value: string;
}

function getSettingNum(key: string, dflt: number): number {
  try {
    const r = db.prepare(`SELECT value FROM app_settings WHERE key = ?`).get(key) as
      | KvRow
      | undefined;
    const n = r ? parseInt(r.value, 10) : NaN;
    return Number.isFinite(n) ? n : dflt;
  } catch {
    return dflt;
  }
}

const router = Router();

// Multer Tmp-Storage; final move erfolgt nach Hash-Berechnung
const TMP_DIR = path.join(os.tmpdir(), 'benny-belege-tmp');
const upload = multer({
  dest: TMP_DIR,
  // Hard-limit 100 MB (multer prueft beim Schreiben).
  // Settings-basiertes max_upload_size_mb wird zusaetzlich pro File geprueft.
  limits: { fileSize: 100 * 1024 * 1024 },
  fileFilter: (_req, file, cb) => {
    const allowed = ['.pdf', '.jpg', '.jpeg', '.png'];
    const ext = path.extname(file.originalname).toLowerCase();
    if (allowed.includes(ext)) {
      cb(null, true);
    } else {
      cb(new Error(`Nicht erlaubter Dateityp: ${ext}`));
    }
  },
});

interface UploadResultEntry {
  id: number;
  original_filename: string;
  sha: string;
  duplicate?: boolean;
  existingId?: number;
}

router.post('/upload', upload.array('file', 20), async (req, res, next) => {
  try {
    const files = req.files as Express.Multer.File[] | undefined;
    if (!files || files.length === 0) {
      res.status(400).json({ error: 'Keine Dateien hochgeladen' });
      return;
    }

    const maxBytes = getSettingNum('max_upload_size_mb', 25) * 1024 * 1024;
    const created: UploadResultEntry[] = [];

    for (const file of files) {
      // 1. Settings-basiertes Limit nachtraeglich pruefen
      if (file.size > maxBytes) {
        await fs.unlink(file.path).catch(() => undefined);
        res.status(413).json({
          error: `Datei "${file.originalname}" ueberschreitet ${maxBytes / 1024 / 1024} MB`,
        });
        return;
      }

      // 2. SHA-256
      const sha = await sha256OfFile(file.path);

      // 3. Duplicate-Check
      const existing = duplicateCheckService.findBySha256(sha);
      if (existing) {
        await fs.unlink(file.path).catch(() => undefined);
        created.push({
          id: 0,
          original_filename: file.originalname,
          sha,
          duplicate: true,
          existingId: existing.id,
        });
        continue;
      }

      // 4. Storage-Verzeichnis sicherstellen + Dateinamen bauen
      const today = new Date().toISOString().slice(0, 10);
      const dir = await ensureStorageDir(today);
      const ext = path.extname(file.originalname).toLowerCase();
      const supplier = sanitizeForFilename('unbekannt', 25);
      const filename = `${today}_${supplier}_0-00_eingangsrechnung${ext}`;
      const finalPath = path.join(dir, filename);
      await fs.rename(file.path, finalPath);

      // 5. Receipt + receipt_files anlegen
      const receipt = receiptService.create(req as Request, {
        type: 'eingangsrechnung',
        source: 'manual_upload',
        receipt_date: today,
        status: 'ocr_pending',
        file_hash_sha256: sha,
        original_filename: file.originalname,
        created_via: 'manual_upload',
      });

      db.prepare(
        `
        INSERT INTO receipt_files
          (receipt_id, original_filename, storage_path, sha256, mime_type, file_size_bytes)
        VALUES (?, ?, ?, ?, ?, ?)
      `,
      ).run(receipt.id, file.originalname, finalPath, sha, file.mimetype, file.size);

      // 6. Background-OCR (per setImmediate, blockiert Response nicht)
      const reqRef = req as Request;
      setImmediate(async () => {
        try {
          const ocr = await ocrService.ocrFile(finalPath);
          const parsed = receiptParserService.parse(ocr.text);
          receiptService.applyOcrResult(reqRef, receipt.id, ocr, parsed);
        } catch (err) {
          console.warn(
            `[ocr-bg] receipt ${receipt.id} failed:`,
            (err as Error).message,
          );
          receiptService.markOcrFailed(reqRef, receipt.id);
        }
      });

      created.push({
        id: receipt.id,
        original_filename: file.originalname,
        sha,
      });
    }

    res.status(201).json({ created });
  } catch (err) {
    next(err);
  }
});

export default router;
